export const MOCK_DATA_EMPLOYEES = [
  {
    firstName: 'John',
    lastName: 'Doe',
    dateOfBirth: '1996-11-24',
    startDate: '2021-04-27',
    street: '129 Main St',
    city: 'Wichita',
    state: 'Kansas',
    zipCode: '35301',
    department: 'Engineering',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    dateOfBirth: '1979-10-15',
    startDate: '2022-01-06',
    street: '653 Elm St',
    city: 'Dallas',
    state: 'Texas',
    zipCode: '60610',
    department: 'Engineering',
  },
  {
    firstName: 'Michael',
    lastName: 'Johnson',
    dateOfBirth: '1962-02-12',
    startDate: '2020-11-01',
    street: '640 Oak St',
    city: 'Baltimore',
    state: 'Maryland',
    zipCode: '15038',
    department: 'Human Resources',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    dateOfBirth: '1951-09-03',
    startDate: '2024-06-18',
    street: '366 Pine St',
    city: 'Jackson',
    state: 'Mississippi',
    zipCode: '83868',
    department: 'Legal',
  },
  {
    firstName: 'David',
    lastName: 'Martinez',
    dateOfBirth: '1999-11-01',
    startDate: '2020-04-08',
    street: '574 Maple St',
    city: 'Boston',
    state: 'Massachusetts',
    zipCode: '52931',
    department: 'Engineering',
  },
  {
    firstName: 'Sarah',
    lastName: 'Garcia',
    dateOfBirth: '1995-11-17',
    startDate: '2020-12-21',
    street: '314 Cedar St',
    city: 'Portland',
    state: 'Maine',
    zipCode: '44903',
    department: 'Human Resources',
  },
  {
    firstName: 'James',
    lastName: 'Rodriguez',
    dateOfBirth: '1975-08-17',
    startDate: '2020-02-15',
    street: '846 Birch St',
    city: 'Boise',
    state: 'Idaho',
    zipCode: '18675',
    department: 'Sales',
  },
  {
    firstName: 'Jessica',
    lastName: 'Wilson',
    dateOfBirth: '1963-09-01',
    startDate: '2024-08-29',
    street: '499 Spruce St',
    city: 'Charlotte',
    state: 'North Carolina',
    zipCode: '76108',
    department: 'Sales',
  },
  {
    firstName: 'Daniel',
    lastName: 'Lopez',
    dateOfBirth: '1980-01-30',
    startDate: '2020-03-16',
    street: '592 Walnut St',
    city: 'Atlanta',
    state: 'Georgia',
    zipCode: '74743',
    department: 'Human Resources',
  },
  {
    firstName: 'Laura',
    lastName: 'Gonzalez',
    dateOfBirth: '1991-02-28',
    startDate: '2021-01-05',
    street: '943 Chestnut St',
    city: 'New Orleans',
    state: 'Louisiana',
    zipCode: '49995',
    department: 'Marketing',
  },
  {
    firstName: 'Matthew',
    lastName: 'Hernandez',
    dateOfBirth: '1982-09-30',
    startDate: '2024-06-13',
    street: '592 Willow St',
    city: 'Albuquerque',
    state: 'New Mexico',
    zipCode: '46357',
    department: 'Sales',
  },
  {
    firstName: 'Ashley',
    lastName: 'Moore',
    dateOfBirth: '1976-01-23',
    startDate: '2023-08-02',
    street: '710 Aspen St',
    city: 'Anchorage',
    state: 'Alaska',
    zipCode: '48435',
    department: 'Human Resources',
  },
  {
    firstName: 'Christopher',
    lastName: 'Taylor',
    dateOfBirth: '1956-02-17',
    startDate: '2021-02-03',
    street: '420 Poplar St',
    city: 'New York',
    state: 'New York',
    zipCode: '64007',
    department: 'Sales',
  },
  {
    firstName: 'Amanda',
    lastName: 'Anderson',
    dateOfBirth: '1953-07-20',
    startDate: '2023-11-02',
    street: '912 Fir St',
    city: 'Cheyenne',
    state: 'Wyoming',
    zipCode: '82943',
    department: 'Human Resources',
  },
  {
    firstName: 'Joshua',
    lastName: 'Thomas',
    dateOfBirth: '1969-10-30',
    startDate: '2022-02-13',
    street: '327 Redwood St',
    city: 'Salt Lake City',
    state: 'Utah',
    zipCode: '89561',
    department: 'Sales',
  },
  {
    firstName: 'Megan',
    lastName: 'Jackson',
    dateOfBirth: '1969-05-10',
    startDate: '2021-01-02',
    street: '386 Dogwood St',
    city: 'Baltimore',
    state: 'Maryland',
    zipCode: '93614',
    department: 'Legal',
  },
  {
    firstName: 'Andrew',
    lastName: 'White',
    dateOfBirth: '1983-04-17',
    startDate: '2023-02-14',
    street: '964 Magnolia St',
    city: 'Sioux Falls',
    state: 'South Dakota',
    zipCode: '28311',
    department: 'Engineering',
  },
  {
    firstName: 'Emily',
    lastName: 'Harris',
    dateOfBirth: '1987-05-21',
    startDate: '2024-04-20',
    street: '18 Sycamore St',
    city: 'Trenton',
    state: 'New Jersey',
    zipCode: '96543',
    department: 'Human Resources',
  },
  {
    firstName: 'Ryan',
    lastName: 'Martin',
    dateOfBirth: '1958-08-16',
    startDate: '2022-10-18',
    street: '107 Hickory St',
    city: 'Denver',
    state: 'Colorado',
    zipCode: '18029',
    department: 'Sales',
  },
  {
    firstName: 'Samantha',
    lastName: 'Martinez',
    dateOfBirth: '1964-11-27',
    startDate: '2023-05-21',
    street: '253 Alder St',
    city: 'Burlington',
    state: 'Vermont',
    zipCode: '54048',
    department: 'Sales',
  },
  {
    firstName: 'Tyler',
    lastName: 'Clark',
    dateOfBirth: '1990-09-10',
    startDate: '2023-07-22',
    street: '155 Beech St',
    city: 'Des Moines',
    state: 'Iowa',
    zipCode: '93130',
    department: 'Human Resources',
  },
  {
    firstName: 'Hannah',
    lastName: 'Lewis',
    dateOfBirth: '1959-12-04',
    startDate: '2023-03-21',
    street: '16 Ash St',
    city: 'Baton Rouge',
    state: 'Louisiana',
    zipCode: '48948',
    department: 'Legal',
  },
  {
    firstName: 'Brandon',
    lastName: 'Robinson',
    dateOfBirth: '1963-01-29',
    startDate: '2021-12-19',
    street: '229 Cypress St',
    city: 'Richmond',
    state: 'Virginia',
    zipCode: '58034',
    department: 'Human Resources',
  },
  {
    firstName: 'Olivia',
    lastName: 'Walker',
    dateOfBirth: '1966-03-09',
    startDate: '2022-02-12',
    street: '502 Palm St',
    city: 'New Orleans',
    state: 'Louisiana',
    zipCode: '84102',
    department: 'Engineering',
  },
  {
    firstName: 'Ethan',
    lastName: 'Young',
    dateOfBirth: '1963-07-01',
    startDate: '2021-10-04',
    street: '467 Juniper St',
    city: 'Wichita',
    state: 'Kansas',
    zipCode: '50652',
    department: 'Sales',
  },
  {
    firstName: 'Natalie',
    lastName: 'Allen',
    dateOfBirth: '1959-12-17',
    startDate: '2023-01-04',
    street: '393 Dogwood St',
    city: 'Trenton',
    state: 'New Jersey',
    zipCode: '66362',
    department: 'Human Resources',
  },
  {
    firstName: 'Benjamin',
    lastName: 'King',
    dateOfBirth: '1957-02-11',
    startDate: '2023-01-01',
    street: '755 Cedar St',
    city: 'Trenton',
    state: 'New Jersey',
    zipCode: '99120',
    department: 'Engineering',
  },
  {
    firstName: 'Grace',
    lastName: 'Wright',
    dateOfBirth: '1994-10-21',
    startDate: '2021-09-18',
    street: '210 Maple St',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zipCode: '72032',
    department: 'Engineering',
  },
  {
    firstName: 'Lucas',
    lastName: 'Scott',
    dateOfBirth: '1960-08-16',
    startDate: '2020-01-21',
    street: '178 Birch St',
    city: 'Dover',
    state: 'Delaware',
    zipCode: '28404',
    department: 'Legal',
  },
  {
    firstName: 'Ava',
    lastName: 'Green',
    dateOfBirth: '1954-06-28',
    startDate: '2023-12-25',
    street: '688 Pine St',
    city: 'Frankfort',
    state: 'Kentucky',
    zipCode: '51389',
    department: 'Engineering',
  },
  {
    firstName: 'Henry',
    lastName: 'Baker',
    dateOfBirth: '1992-01-12',
    startDate: '2022-08-03',
    street: '10 Spruce St',
    city: 'Boise',
    state: 'Idaho',
    zipCode: '24134',
    department: 'Human Resources',
  },
  {
    firstName: 'Sofia',
    lastName: 'Gonzalez',
    dateOfBirth: '1988-07-28',
    startDate: '2020-02-20',
    street: '793 Elm St',
    city: 'Wichita',
    state: 'Kansas',
    zipCode: '98609',
    department: 'Marketing',
  },
  {
    firstName: 'Jack',
    lastName: 'Perez',
    dateOfBirth: '1962-04-18',
    startDate: '2022-11-09',
    street: '345 Oak St',
    city: 'Cheyenne',
    state: 'Wyoming',
    zipCode: '71490',
    department: 'Engineering',
  },
  {
    firstName: 'Mia',
    lastName: 'Hill',
    dateOfBirth: '1990-10-04',
    startDate: '2022-03-05',
    street: '909 Pine St',
    city: 'Washington',
    state: 'District Of Columbia',
    zipCode: '40106',
    department: 'Marketing',
  },
  {
    firstName: 'Alexander',
    lastName: 'Adams',
    dateOfBirth: '1986-11-11',
    startDate: '2021-08-26',
    street: '243 Maple St',
    city: 'St. Louis',
    state: 'Missouri',
    zipCode: '21236',
    department: 'Human Resources',
  },
  {
    firstName: 'Ella',
    lastName: 'Nelson',
    dateOfBirth: '1956-04-05',
    startDate: '2020-03-01',
    street: '216 Cedar St',
    city: 'New Orleans',
    state: 'Louisiana',
    zipCode: '28208',
    department: 'Legal',
  },
  {
    firstName: 'William',
    lastName: 'Carter',
    dateOfBirth: '1952-02-01',
    startDate: '2023-07-16',
    street: '317 Birch St',
    city: 'Providence',
    state: 'Rhode Island',
    zipCode: '87289',
    department: 'Sales',
  },
  {
    firstName: 'Avery',
    lastName: 'Mitchell',
    dateOfBirth: '1962-08-14',
    startDate: '2020-06-19',
    street: '501 Elm St',
    city: 'Santa Fe',
    state: 'New Mexico',
    zipCode: '86586',
    department: 'Sales',
  },
  {
    firstName: 'Liam',
    lastName: 'Perez',
    dateOfBirth: '1953-03-07',
    startDate: '2024-06-25',
    street: '696 Oak St',
    city: 'Atlanta',
    state: 'Georgia',
    zipCode: '66989',
    department: 'Human Resources',
  },
  {
    firstName: 'Chloe',
    lastName: 'Roberts',
    dateOfBirth: '1965-07-05',
    startDate: '2021-12-13',
    street: '35 Pine St',
    city: 'Jackson',
    state: 'Mississippi',
    zipCode: '82227',
    department: 'Engineering',
  },
  {
    firstName: 'Mason',
    lastName: 'Turner',
    dateOfBirth: '1957-06-02',
    startDate: '2023-11-15',
    street: '715 Cedar St',
    city: 'New York',
    state: 'New York',
    zipCode: '77800',
    department: 'Human Resources',
  },
  {
    firstName: 'Zoe',
    lastName: 'Phillips',
    dateOfBirth: '1952-04-20',
    startDate: '2022-03-21',
    street: '853 Elm St',
    city: 'Portland',
    state: 'Maine',
    zipCode: '43745',
    department: 'Engineering',
  },
  {
    firstName: 'Logan',
    lastName: 'Campbell',
    dateOfBirth: '1996-04-07',
    startDate: '2020-04-30',
    street: '221 Oak St',
    city: 'Indianapolis',
    state: 'Indiana',
    zipCode: '93462',
    department: 'Engineering',
  },
  {
    firstName: 'Lily',
    lastName: 'Evans',
    dateOfBirth: '1976-12-03',
    startDate: '2023-11-17',
    street: '315 Pine St',
    city: 'Richmond',
    state: 'Virginia',
    zipCode: '85147',
    department: 'Human Resources',
  },
  {
    firstName: 'Jackson',
    lastName: 'Edwards',
    dateOfBirth: '1989-08-04',
    startDate: '2021-01-22',
    street: '706 Maple St',
    city: 'Bismarck',
    state: 'North Dakota',
    zipCode: '36441',
    department: 'Marketing',
  },
  {
    firstName: 'Grace',
    lastName: 'Collins',
    dateOfBirth: '2000-03-27',
    startDate: '2024-03-18',
    street: '964 Oak St',
    city: 'Providence',
    state: 'Rhode Island',
    zipCode: '48592',
    department: 'Marketing',
  },
  {
    firstName: 'Evelyn',
    lastName: 'Stewart',
    dateOfBirth: '2000-11-05',
    startDate: '2020-07-07',
    street: '484 Elm St',
    city: 'Detroit',
    state: 'Michigan',
    zipCode: '69846',
    department: 'Legal',
  },
  {
    firstName: 'Aiden',
    lastName: 'Morris',
    dateOfBirth: '1963-11-13',
    startDate: '2021-03-03',
    street: '96 Pine St',
    city: 'Saipan',
    state: 'Northern Mariana Islands',
    zipCode: '72984',
    department: 'Legal',
  },
  {
    firstName: 'Scarlett',
    lastName: 'Rogers',
    dateOfBirth: '1990-12-21',
    startDate: '2021-07-01',
    street: '499 Maple St',
    city: 'Lincoln',
    state: 'Nebraska',
    zipCode: '30222',
    department: 'Legal',
  },
  {
    firstName: 'Oliver',
    lastName: 'Reed',
    dateOfBirth: '1962-12-07',
    startDate: '2023-11-29',
    street: '964 Oak St',
    city: 'Phoenix',
    state: 'Arizona',
    zipCode: '82623',
    department: 'Engineering',
  },
];
